development:
  adapter: postgresql
  database: Figaro.env.database
  pool: 5
  timeout: 5000
  host: localhost
  username: Figaro.env.username
  password: Figaro.env.password

test:
  adapter: postgresql
  database: ENV["DATABASE"]
  pool: 5
  timeout: 5000
  host: localhost
  username: ENV["USERNAME"]
  password: ENV["PASSWORD"]

production:
  adapter: postgresql
  database: ENV["DATABASE"]
  pool: 5
  timeout: 5000
  username: ENV["USERNAME"]
  password: ENV["PASSWORD"]
