development:
  adapter: postgresql
  database: everything_dev
  pool: 5
  timeout: 5000
  username: vagrant
  password: vagrant

test:
  adapter: postgresql
  database: everything_test
  pool: 5
  timeout: 5000
  username: vagrant
  password: vagrant

production:
  adapter: postgresql
  database: everything_production
  pool: 5
  timeout: 5000
  username: vagrant
  password: vagrant
