require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComputersController do

  # This should return the minimal set of attributes required to create a valid
  # Computer. As you add validations to Computer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComputersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all computers as @computers" do
      computer = Computer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:computers).should eq([computer])
    end
  end

  describe "GET show" do
    it "assigns the requested computer as @computer" do
      computer = Computer.create! valid_attributes
      get :show, {:id => computer.to_param}, valid_session
      assigns(:computer).should eq(computer)
    end
  end

  describe "GET new" do
    it "assigns a new computer as @computer" do
      get :new, {}, valid_session
      assigns(:computer).should be_a_new(Computer)
    end
  end

  describe "GET edit" do
    it "assigns the requested computer as @computer" do
      computer = Computer.create! valid_attributes
      get :edit, {:id => computer.to_param}, valid_session
      assigns(:computer).should eq(computer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Computer" do
        expect {
          post :create, {:computer => valid_attributes}, valid_session
        }.to change(Computer, :count).by(1)
      end

      it "assigns a newly created computer as @computer" do
        post :create, {:computer => valid_attributes}, valid_session
        assigns(:computer).should be_a(Computer)
        assigns(:computer).should be_persisted
      end

      it "redirects to the created computer" do
        post :create, {:computer => valid_attributes}, valid_session
        response.should redirect_to(Computer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved computer as @computer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Computer.any_instance.stub(:save).and_return(false)
        post :create, {:computer => {}}, valid_session
        assigns(:computer).should be_a_new(Computer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Computer.any_instance.stub(:save).and_return(false)
        post :create, {:computer => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested computer" do
        computer = Computer.create! valid_attributes
        # Assuming there are no other computers in the database, this
        # specifies that the Computer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Computer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => computer.to_param, :computer => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested computer as @computer" do
        computer = Computer.create! valid_attributes
        put :update, {:id => computer.to_param, :computer => valid_attributes}, valid_session
        assigns(:computer).should eq(computer)
      end

      it "redirects to the computer" do
        computer = Computer.create! valid_attributes
        put :update, {:id => computer.to_param, :computer => valid_attributes}, valid_session
        response.should redirect_to(computer)
      end
    end

    describe "with invalid params" do
      it "assigns the computer as @computer" do
        computer = Computer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Computer.any_instance.stub(:save).and_return(false)
        put :update, {:id => computer.to_param, :computer => {}}, valid_session
        assigns(:computer).should eq(computer)
      end

      it "re-renders the 'edit' template" do
        computer = Computer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Computer.any_instance.stub(:save).and_return(false)
        put :update, {:id => computer.to_param, :computer => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested computer" do
      computer = Computer.create! valid_attributes
      expect {
        delete :destroy, {:id => computer.to_param}, valid_session
      }.to change(Computer, :count).by(-1)
    end

    it "redirects to the computers list" do
      computer = Computer.create! valid_attributes
      delete :destroy, {:id => computer.to_param}, valid_session
      response.should redirect_to(computers_url)
    end
  end

end
