require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PeripheralsController do

  # This should return the minimal set of attributes required to create a valid
  # Peripheral. As you add validations to Peripheral, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PeripheralsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all peripherals as @peripherals" do
      peripheral = Peripheral.create! valid_attributes
      get :index, {}, valid_session
      assigns(:peripherals).should eq([peripheral])
    end
  end

  describe "GET show" do
    it "assigns the requested peripheral as @peripheral" do
      peripheral = Peripheral.create! valid_attributes
      get :show, {:id => peripheral.to_param}, valid_session
      assigns(:peripheral).should eq(peripheral)
    end
  end

  describe "GET new" do
    it "assigns a new peripheral as @peripheral" do
      get :new, {}, valid_session
      assigns(:peripheral).should be_a_new(Peripheral)
    end
  end

  describe "GET edit" do
    it "assigns the requested peripheral as @peripheral" do
      peripheral = Peripheral.create! valid_attributes
      get :edit, {:id => peripheral.to_param}, valid_session
      assigns(:peripheral).should eq(peripheral)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Peripheral" do
        expect {
          post :create, {:peripheral => valid_attributes}, valid_session
        }.to change(Peripheral, :count).by(1)
      end

      it "assigns a newly created peripheral as @peripheral" do
        post :create, {:peripheral => valid_attributes}, valid_session
        assigns(:peripheral).should be_a(Peripheral)
        assigns(:peripheral).should be_persisted
      end

      it "redirects to the created peripheral" do
        post :create, {:peripheral => valid_attributes}, valid_session
        response.should redirect_to(Peripheral.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved peripheral as @peripheral" do
        # Trigger the behavior that occurs when invalid params are submitted
        Peripheral.any_instance.stub(:save).and_return(false)
        post :create, {:peripheral => {}}, valid_session
        assigns(:peripheral).should be_a_new(Peripheral)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Peripheral.any_instance.stub(:save).and_return(false)
        post :create, {:peripheral => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested peripheral" do
        peripheral = Peripheral.create! valid_attributes
        # Assuming there are no other peripherals in the database, this
        # specifies that the Peripheral created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Peripheral.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => peripheral.to_param, :peripheral => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested peripheral as @peripheral" do
        peripheral = Peripheral.create! valid_attributes
        put :update, {:id => peripheral.to_param, :peripheral => valid_attributes}, valid_session
        assigns(:peripheral).should eq(peripheral)
      end

      it "redirects to the peripheral" do
        peripheral = Peripheral.create! valid_attributes
        put :update, {:id => peripheral.to_param, :peripheral => valid_attributes}, valid_session
        response.should redirect_to(peripheral)
      end
    end

    describe "with invalid params" do
      it "assigns the peripheral as @peripheral" do
        peripheral = Peripheral.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Peripheral.any_instance.stub(:save).and_return(false)
        put :update, {:id => peripheral.to_param, :peripheral => {}}, valid_session
        assigns(:peripheral).should eq(peripheral)
      end

      it "re-renders the 'edit' template" do
        peripheral = Peripheral.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Peripheral.any_instance.stub(:save).and_return(false)
        put :update, {:id => peripheral.to_param, :peripheral => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested peripheral" do
      peripheral = Peripheral.create! valid_attributes
      expect {
        delete :destroy, {:id => peripheral.to_param}, valid_session
      }.to change(Peripheral, :count).by(-1)
    end

    it "redirects to the peripherals list" do
      peripheral = Peripheral.create! valid_attributes
      delete :destroy, {:id => peripheral.to_param}, valid_session
      response.should redirect_to(peripherals_url)
    end
  end

end
